FROM arm64v8/spark:3.5.1-scala2.12-java17-ubuntu

USER root

RUN set -ex; \
    apt-get update; \
    apt-get install -y python3 python3-pip; \
    apt-get install -y r-base r-base-dev; \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip
RUN pip3 install pyspark
RUN pip install delta-spark==3.0.0
ENV R_HOME /usr/lib/R

# # # Modify permissions for the spark user
RUN mkdir -p /home/spark && \
    chown -R spark:spark /home/spark

# https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-how-to-deploy?tabs=Ubuntu
# RUN wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb \
#     && dpkg -i packages-microsoft-prod.deb \
#     && apt-get update \
#     && apt-get install libfuse3-dev fuse3 \
    # && apt-get install -y blobfuse

# RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb \
#     && dpkg -i packages-microsoft-prod.deb \
#     && apt-get update \
#     && apt-get install libfuse3-dev fuse3 \
#     && apt-get install -y blobfuse2
# RUN apt-get update && apt install nano


# RUN apt-get update && apt-get install libcurl3-gnutls && apt-get install -y fuse

# RUN apt-get update && \
#     apt-get install -y fuse && \
#     rm -rf /var/lib/apt/lists/*

# USER spark